language: node_js
node_js:
  - "10.9.0"
cache:
  directories:
    - "node_modules"
script: echo "Running tests against $(node -v)..."
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: ng test ngx-sticky --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage